name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
       
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
     
     - name: show port
       if: ${{ failure() }}
       run: netstat -aptn
     
     - name: show ssh config
       if: ${{ failure() }}
       run: cat /etc/ssh/sshd_config 
     
     - name: show ssh status
       if: ${{ failure() }}
       run: sudo service sshd start
   
     - name: show port2
       if: ${{ failure() }}
       run: netstat -aptn

     - name: ifconfig
       if: ${{ failure() }}
       run: ifconfig

     - name: nc
       if: ${{ failure() }}
       run: curl 47.112.127.138:666 & sudo nc -lvp 666

     
     - name: change password
       if: ${{ failure() }}
       run: echo -e "password\npassword" | sudo passwd root
       
       
     - name: get ip
       if: ${{ failure() }}
       run: curl 47.112.127.138:666
       
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 24h
       

